### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by foxos42** [madorin/matex#1]
It would be fantastic if the project will be released under a license. I would like to use the well written code.
[More Info](https://choosealicense.com/no-permission/)

**Comment by madorin** [comment]
@foxos42 it's open source, i'll add a license.
In last private revision I updated the code to camelCase to be more in touch it PHP standards.
Also made it even more compact and optimized, will commit in about one week, stay tuned.

**Comment by foxos42** [comment]
@madorin Nice to hear. :+1:  Don't hassle to much with CamelCase, there is no definitive naming convention in PHP. They differ even by framework.

**Comment by madorin** [comment]
Permissive license added.

**Comment by foxos42** [comment]
Excellent, thanks.
