### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by dyanakiev** [madorin/matex#14]
**Is your feature request related to a problem? Please describe.**
Currently its not possible to round

**Describe the solution you'd like**
Will be awesome if there is a way to use it that way for example i want to do `round(0.7/100)` or something else..

**Describe alternatives you've considered**
Currently im using plain php, will like to switch to a lib like this so i can create dynamic calculations via user inputs for example.

**Additional context**
Is there any alternative package to this that supports round? I couldn't find any maybe im searching the wrong keywrods.

**Comment by madorin** [comment]
@dyanakiev , you may connect any function to expression engine, including round .. its simple, check the examples in readme.
