### ISSUE TITLE
Composer not installing for my PHP version.

### ISSUE THREAD

**Issue by sanmayad** [madorin/matex#18]
My PHP Version is 7.2.34 and composer is not installing it.

What's the PHP version that it needs?

**Comment by madorin** [comment]
@sanmayad , it require 7.3 in composer.json now. I'll check for 7.2 compatibility. Saw PHP v7.3 is the default  version in major linux distros, so tought it is enough...

**Comment by sanmayad** [comment]
@madorin I checked your code, seems like it should be compatible with 7.2 but not below it.

Please check and update

**Comment by madorin** [comment]
@sanmayad , lowered the version to v7.2, give it a try
