### ISSUE TITLE
Assign a value to a variable inside an expression

### ISSUE THREAD

**Issue by koosvanderkolk** [madorin/matex#19]
Not entirely sure whether this is a bug or a feature request.

In my code I have:

`$this->matex->execute('a=random()');`

Unfortunately, this throws an exception: Exception: Unknown variable: a in Evaluator->getVariable(). Am I correct that this is not supposed to work in the current version?

**Comment by madorin** [comment]
@koosvanderkolk , not sure if this will be ever implemented.
Check if this works for you, $a = $matex->execute('expression here');

Matex is designed to evalate a single expression, like an Excel formula.
It does not evaluate multiple statements/code, like php interpretter itself.
For code executions, you may consider eval( but only for "trusted" code, as it is not safe.

**Comment by koosvanderkolk** [comment]
Thanks! I indeed solved this by a wrapper class. Something like:

```
$expr = 'a=random()';
$exprAsArray = explode('=', $expr);
$varToCalculate = $exprAsArray[0];
$expression = $exprAsArray[1];
$this->evaluator->variables[$varToCalculate] = $this->evaluator->execute($expression);
```

**Comment by madorin** [comment]
In our projects we have two separate columns .. like "Field | Formula", instead of exploding the expression.

Note the "=" sign may later cause problems, if i'll implement later boolean operators, like "2 * a <= b".
