### ISSUE TITLE
Add composer.json and add this to https://packagist.org/

### ISSUE THREAD

**Issue by r-nicol** [madorin/matex#4]
**Is your feature request related to a problem? Please describe.**
This project looks really handy, but without having it on https://packagist.org/ it makes installing and maintenance very old school. E.g. my current laravel project I have to download the files and manually autoload them.
 
**Describe the solution you'd like**
Please can you add a composer.json file to the project and submit the project to https://packagist.org/ This would allow for easier installation and maintenance, when used inside other projects.
 
**Describe alternatives you've considered**
There ain't one

**Additional context**
-

**Comment by madorin** [comment]
Okay, ill add a composer.json file.
This was not a priority for me as we have our autoloader in our projects, PSR compatible.

**Comment by r-nicol** [comment]
Thanks a lot I really appreciate it.

**Comment by WilliamStam** [comment]
add another 1 looking for a composer.json file :D

**Comment by r-nicol** [comment]
Any chance for that composer file soon?

**Comment by timothymarois** [comment]
Wish this was here, otherwise have to find another package thats composer ready. Looking through the rest of the issues, not sure if the owner updates this anymore, it looks like he responds with a hope to update, but doesn't actually look like its ever committed. That's unfortunate because this looked like a good option.

**Comment by dyanakiev** [comment]
@timothymarois did you find better package?

**Comment by r3sist** [comment]
@dyanakiev added packagist/composer for myself: https://github.com/r3sist/matex It's not recommended to use it for obvious reasons, but you may fork it also.
