### ISSUE TITLE
Make variables case sensitive (not only Lower Case)

### ISSUE THREAD

**Issue by felix-the-real-cat** [madorin/matex#5]
**Is your feature request related to a problem? Please describe.**
I have a use case where my variables are UCased (i.e. A, B, ...). I was surprised to have to use strict Lcase variables because your Evaluator is LCasing the formula passed to it.

**Describe the solution you'd like**
Let the user choose the case sensitivity via an option and by default use the exact formula that the user provides (no LCasing).
OR
LCase all variables passed to the evaluator (this one is not my favorite).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A.

**Comment by madorin** [comment]
@felix-the-real-cat, it do LCasing to eliminate in some way case sensitivity on functions/variables, especially when you do late binding of variable in case, or db file lookup.
For now, you can bind variable LCased and they should work.
But I'll think on it, for a more inteligent solution.

**Comment by felix-the-real-cat** [comment]
OK. I get the reason ! Good to know !

**Comment by madorin** [comment]
No case sensity for no.
Usually formulas may be written by end-users and no sense to bother them with the case.
